### ISSUE TITLE
R.raw.timestamp error

### ISSUE THREAD

**Issue by AllPlatform** [jeffboody/loax-server#1]
`A3DResource r = new A3DResource(this, R.raw.timestamp);`
![unknown](https://user-images.githubusercontent.com/44525248/89315689-59a2a280-d6a5-11ea-8feb-e04edac18a7d.png)

pls help me

**Comment by jeffboody** [comment]
It is missing a resource file called timestamp.raw which I normally created
at build time by building from the command line using ant.

https://github.com/jeffboody/loax-server/blob/master/build-java.sh

I don't think ant is supported anymore but you should be able to create
this file manually and then build using Android Studio.

This timestamp.raw file is used to determine when the app resources have
been updated (just a font texture for this app). The app resources are
copied from the resources to the sdcard since they are needed by native
code. When this code was created the ANativeActivity didn't exist yet and I
didn't know of any other way to access files from native code.

**Comment by AllPlatform** [comment]
I encountered an error during compile Android.mk

`Build command failed.
Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\21.0.6113669\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Administrator\StudioProjects\project1\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Administrator\StudioProjects\project1\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=C:/Users/Administrator/StudioProjects/project1/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Administrator\StudioProjects\project1\app\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}`

`C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/21.0.6113669/build//../build/core/build-binary.mk:651: Android NDK: Module a3d depends on undefined modules: pak texgz expat    
C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/21.0.6113669/build//../build/core/build-binary.mk:664: *** Android NDK: Note that old versions of ndk-build silently ignored this error case. If your project worked on those versions, the missing libraries were not needed and you can remove those dependencies from the module to fix your build. Alternatively, set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies.    .  Stop.`

![unknown](https://user-images.githubusercontent.com/44525248/89369795-53dea880-d709-11ea-8334-7a94c9c1ac0d.png)

**Comment by AllPlatform** [comment]
@jeffboody 
Can you tell me the version of NDK that you have compiled the app Pls Pls

**Comment by jeffboody** [comment]
I can't tell you what version that I used last for this project but it
looks like you need to update the submodules.

git submodule init
git submodule update

**Comment by jeffboody** [comment]
I forgot this project was created with a very old version of the Android NDK and no longer builds. I've updated the code so that it should now work with current Android Studio builds and the branch loax2020. You can sync these changes as follows then build with Android Studio.

$ git clone git@github.com:jeffboody/loax-server.git
Cloning into 'loax-server'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 362 (delta 5), reused 84 (delta 5), pack-reused 278
Receiving objects: 100% (362/362), 189.44 KiB | 1.55 MiB/s, done.
Resolving deltas: 100% (131/131), done.

$ cd loax-server/

$ git checkout -b loax2020 origin/loax2020
Branch 'loax2020' set up to track remote branch 'loax2020' from 'origin'.
Switched to a new branch 'loax2020'

$ git submodule init
Submodule 'a3d-fonts' (git@github.com:jeffboody/a3d-fonts) registered for path 'a3d-fonts'
Submodule 'app/src/main/cpp/a3d' (git@github.com:jeffboody/a3d-native) registered for path 'app/src/main/cpp/a3d'
Submodule 'app/src/main/cpp/loax' (git@github.com:jeffboody/loax) registered for path 'app/src/main/cpp/loax'
Submodule 'app/src/main/cpp/net' (git@github.com:jeffboody/net) registered for path 'app/src/main/cpp/net'
Submodule 'app/src/main/java/com/jeffboody/a3d' (git@github.com:jeffboody/a3d-java) registered for path 'app/src/main/java/com/jeffboody/a3d'

$ git submodule update
Cloning into '/home/jeffboody/src/test/loax-server/a3d-fonts'...
Cloning into '/home/jeffboody/src/test/loax-server/app/src/main/cpp/net'...
Cloning into '/home/jeffboody/src/test/loax-server/app/src/main/cpp/a3d'...
Cloning into '/home/jeffboody/src/test/loax-server/app/src/main/cpp/loax'...
Cloning into '/home/jeffboody/src/test/loax-server/app/src/main/java/com/jeffboody/a3d'...
Submodule path 'a3d-fonts': checked out 'c33d540b65bd6906c16ff9a198f53740864c171d'
Submodule path 'app/src/main/cpp/a3d': checked out 'a085231bf0755f21e4504ea716d3c1bf6bede162'
Submodule path 'app/src/main/cpp/loax': checked out '8636ea35910fe8522ccd85312f807d18eb507434'
Submodule path 'app/src/main/cpp/net': checked out 'afbc81c08dac295f0ba319c0c24ca8a541634048'
Submodule path 'app/src/main/java/com/jeffboody/a3d': checked out 'cfbb436d70896ec86724cb52f12f1b018c0f5ae8'
